#  menu items
[[main]]
  name = "VENT"
  weight = 4
  url = "blog/"

[[main]]
  name = "Notes"
  weight = 1
  url = "topics/"

[[main]]
  name = "fucking Test function i forgot to remove"
  weight = 2
  url = "https://www.linkedin.com/in/reeshav-mukherjee-7887a5193/"

# [[main]]
#   name = "Blog"
#   weight = 3
#   url = "blog/"